### ISSUE TITLE
Optiplex 990: Not Ready on ReadKeyStroke

### ISSUE THREAD

**Issue by Matt8898** [TomatOrg/TomatBoot-UEFI#1]
![optiplex_key](https://user-images.githubusercontent.com/9578391/69920545-bbad6700-1489-11ea-9255-6f9dca4176cf.JPG)

Tomatboot fails to read key presses on any menu, this can be worked around by removing the assert for now.

**Comment by Itay2805** [comment]
That is actually kinda strange because we use WaitForEvent before calling this function, so in theory it should be ready...
